### ISSUE TITLE
Add guzzle 7 support

### ISSUE THREAD

**Issue by VarroReve** [Ne-Lexa/http-client-simple-cache#1]
Please update to "guzzlehttp/guzzle": "^6.5 | ^7.0" in `composer.json` so I can use `Ne-Lexa/google-play-scraper` in my new Laravel project. Thank you.

**Comment by Ne-Lexa** [comment]
@VarroReve Unfortunately, this cannot be done due to strict typing, preserving current functionality.
In Guzzle 7 all calls to `->request(` must return `Response`, while in Guzzle 6 `mixed` was returned.
